# Generated by Django 5.2.1 on 2025-05-29 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('clear_elasticsearch', 'Clear Elasticsearch'), ('update_sof_elk', 'Update SOF-ELK'), ('nfdump_to_sof_elk', 'Process NetFlow'), ('aws_vpcflow_to_sof_elk', 'Process AWS VPC Flow'), ('azure_vpcflow_to_sof_elk', 'Process Azure VPC Flow'), ('delete_log_files', 'Delete Log Files')], max_length=30)),
                ('parameters', models.JSONField(default=dict)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('log_type', models.CharField(choices=[('aws', 'AWS CloudTrail'), ('azure', 'Azure Logs'), ('gcp', 'Google Compute Platform'), ('gws', 'Google Workspace'), ('httpd', 'Apache HTTP'), ('kape', 'KAPE Triage'), ('kubernetes', 'Kubernetes'), ('microsoft365', 'Microsoft 365'), ('nfarch', 'NetFlow Archive'), ('passivedns', 'Passive DNS'), ('plaso', 'Plaso CSV'), ('syslog', 'Syslog'), ('zeek', 'Zeek Network Security')], max_length=20)),
                ('original_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('size', models.BigIntegerField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('elasticsearch_status', models.CharField(default='unknown', max_length=20)),
                ('logstash_status', models.CharField(default='unknown', max_length=20)),
                ('kibana_status', models.CharField(default='unknown', max_length=20)),
                ('disk_usage', models.JSONField(default=dict)),
                ('indices_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'System statuses',
                'ordering': ['-timestamp'],
            },
        ),
    ]
